# Generated by Django 5.1.1 on 2025-02-11 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PTID", models.CharField(max_length=50, null=True)),
                ("PTGENDER", models.IntegerField(choices=[(1, "Male"), (2, "Female")])),
                (
                    "PTRACCAT",
                    models.IntegerField(
                        choices=[
                            (1, "American Indian or Alaskan Native"),
                            (2, "Asian"),
                            (3, "Native Haiwaian or other Pacific Islander"),
                            (4, "Black or African American"),
                            (5, "White"),
                            (6, "More than once race"),
                            (7, "Uknown"),
                            (8, "Native American"),
                            (9, "Other Pacific Islander"),
                        ]
                    ),
                ),
                (
                    "FHQSIBAD",
                    models.IntegerField(
                        choices=[(0, "No"), (1, "Yes"), (2, "Unknown")]
                    ),
                ),
            ],
        ),
    ]
