# Generated by Django 5.1.1 on 2025-02-11 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="AGE",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="DIAGNOSIS",
            field=models.IntegerField(
                choices=[(1, "CN"), (2, "MCI"), (3, "DEMENTIA")], null=True
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="DXDDUE",
            field=models.IntegerField(choices=[(1, "AD"), (2, "NOT AD")], null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="GENOTYPE",
            field=models.IntegerField(
                choices=[
                    (0, "2/2"),
                    (1, "2/3"),
                    (2, "2/4"),
                    (3, "3/3"),
                    (4, "3/4"),
                    (5, "4/4"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="MMSCORE",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="FHQSIBAD",
            field=models.IntegerField(
                choices=[(0, "No"), (1, "Yes"), (2, "Unknown")], null=True
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="PTGENDER",
            field=models.IntegerField(choices=[(1, "Male"), (2, "Female")], null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="PTRACCAT",
            field=models.IntegerField(
                choices=[
                    (1, "American Indian or Alaskan Native"),
                    (2, "Asian"),
                    (3, "Native Haiwaian or other Pacific Islander"),
                    (4, "Black or African American"),
                    (5, "White"),
                    (6, "More than once race"),
                    (7, "Uknown"),
                    (8, "Native American"),
                    (9, "Other Pacific Islander"),
                ],
                null=True,
            ),
        ),
    ]
