# Generated by Django 5.1.1 on 2025-04-23 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0002_patient_age_patient_diagnosis_patient_dxddue_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="PTID", new_name="SUBJECT_ID",
        ),
        migrations.RemoveField(model_name="patient", name="DIAGNOSIS",),
        migrations.RemoveField(model_name="patient", name="DXDDUE",),
        migrations.RemoveField(model_name="patient", name="FHQSIBAD",),
        migrations.RemoveField(model_name="patient", name="GENOTYPE",),
        migrations.RemoveField(model_name="patient", name="PTGENDER",),
        migrations.RemoveField(model_name="patient", name="PTRACCAT",),
        migrations.AddField(
            model_name="patient",
            name="ASF",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="CDR",
            field=models.IntegerField(
                choices=[
                    (0, "Non Demented"),
                    (0.5, "Very Mild AD"),
                    (1, "Mild AD"),
                    (2, "Moderate AD"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="EDUCATION",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="ETIV",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="GENDER",
            field=models.IntegerField(choices=[(0, "Male"), (1, "Female")], null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="GROUP",
            field=models.IntegerField(
                choices=[(0, "Non Demented"), (1, "Demented"), (2, "Converted")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="HAND",
            field=models.IntegerField(choices=[(0, "Right"), (1, "Left")], null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="MRI_ID",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="NWBV",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="patient",
            name="SES",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
