# Generated by Django 5.1.1 on 2025-04-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0002_remove_patient_health_provider_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="treating",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="apiapp.patient",
            ),
        ),
    ]
