# Generated by Django 5.1.1 on 2025-04-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0003_alter_userprofile_treating"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="PT_F_NAME",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="PT_LAST_NAME",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
