# Generated by Django 5.1.1 on 2025-04-24 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0004_patient_pt_f_name_patient_pt_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="Doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
