# Generated by Django 5.1.1 on 2025-04-24 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0005_patient_doctor"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="date_of_birth",),
    ]
