# Generated by Django 5.1.1 on 2025-04-25 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0006_remove_user_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="Doctor",),
    ]
