# Generated by Django 5.1.1 on 2025-04-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0007_remove_patient_doctor"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="treating",),
        migrations.AddField(
            model_name="patient",
            name="Doctor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_to",
                to="apiapp.userprofile",
            ),
        ),
    ]
