# Generated by Django 5.1.1 on 2025-04-25 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0008_remove_userprofile_treating_patient_doctor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient", old_name="Doctor", new_name="assigned_to",
        ),
    ]
