# Generated by Django 5.1.1 on 2025-04-28 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0010_patient_flagged_by_alter_patient_age_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("VISIT_ID", models.CharField(max_length=50, null=True, unique=True)),
                (
                    "GROUP",
                    models.IntegerField(
                        choices=[
                            (0, "Non Demented"),
                            (1, "Demented"),
                            (2, "Converted"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "EDUCATION",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "SES",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "CDR",
                    models.IntegerField(
                        choices=[
                            (0, "Non Demented"),
                            (0.5, "Very Mild AD"),
                            (1, "Mild AD"),
                            (2, "Moderate AD"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "MMSCORE",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(30),
                        ],
                    ),
                ),
                (
                    "AGE",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ETIV",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "NWBV",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ASF",
                    models.FloatField(
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="patient", name="AGE",),
        migrations.RemoveField(model_name="patient", name="ASF",),
        migrations.RemoveField(model_name="patient", name="CDR",),
        migrations.RemoveField(model_name="patient", name="EDUCATION",),
        migrations.RemoveField(model_name="patient", name="ETIV",),
        migrations.RemoveField(model_name="patient", name="GROUP",),
        migrations.RemoveField(model_name="patient", name="MMSCORE",),
        migrations.RemoveField(model_name="patient", name="NWBV",),
        migrations.RemoveField(model_name="patient", name="SES",),
    ]
