# Generated by Django 5.1.1 on 2025-04-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0012_visit_visits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visit", old_name="visits", new_name="patient",
        ),
    ]
