# Generated by Django 5.1.1 on 2025-04-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0013_rename_visits_visit_patient"),
    ]

    operations = [
        migrations.RemoveField(model_name="visit", name="VISIT_ID",),
    ]
