# Generated by Django 5.1.1 on 2025-04-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0015_visit_date_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="img",
            field=models.ImageField(default="", upload_to="pics_user"),
        ),
        migrations.CreateModel(
            name="MRI_IMG",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(default="", upload_to="pics_user")),
                (
                    "patient_img",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="MRI_image",
                        to="apiapp.patient",
                    ),
                ),
            ],
        ),
    ]
