# Generated by Django 5.1.1 on 2025-04-30 22:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "apiapp",
            "0017_remove_prediction_subject_id_remove_visit_date_visit_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="VISIT",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
