# Generated by Django 5.1.1 on 2025-04-30 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0020_alter_visit_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="apiapp.patient",
            ),
        ),
    ]
