# Generated by Django 5.1.1 on 2025-05-01 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0021_alter_visit_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="AGE",
            field=models.IntegerField(
                null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
