# Generated by Django 5.1.1 on 2025-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0025_prediction_risk_prediction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mri_img",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="imgs/"),
        ),
    ]
