# Generated by Django 5.1.1 on 2025-05-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0026_alter_mri_img_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="patient", name="MRI_ID",),
        migrations.AddField(
            model_name="mri_img",
            name="MRI_ID",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
