# Generated by Django 5.1.1 on 2025-05-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0027_remove_patient_mri_id_mri_img_mri_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="img",
            field=models.ImageField(
                blank=True,
                default="media/imgs/default-avatar.jpg",
                null=True,
                upload_to="imgs/",
            ),
        ),
    ]
