# Generated by Django 5.1.1 on 2025-05-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0028_alter_userprofile_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="img",),
    ]
