# Generated by Django 4.2.16 on 2025-05-06 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiapp", "0029_remove_userprofile_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="CDR",
            field=models.FloatField(
                choices=[
                    (0, "Non Demented"),
                    (0.5, "Very Mild AD"),
                    (1, "Mild AD"),
                    (2, "Moderate AD"),
                ],
                null=True,
            ),
        ),
    ]
